import threading
import time
lock_1=threading.Lock()
lock_2=threading.Lock()
def func_1():
    print("start func1")
    lock_1.acquire()
    print("申请锁一")
    time.sleep(2)
    print("func_1等待锁二")
    lock_2.acquire()
    print("申请锁二")
    lock_2.release()
    print("释放锁二")
    lock_1.release()
    print("释放锁一")
    print("func_1 Done")
def func_2():
    print("Start func2")
    lock_2.acquire()
    print("申请锁二")
    time.sleep(4)
    print("func_2等待lock_1")
    lock_1.acquire()
    print("申请锁一")
    lock_1.release()
    print("释放锁一")
    lock_2.release()
    print("释放锁二")
    print("end func——2")
if __name__ == '__main__':
    t1=threading.Thread(target=func_1,args=() )
    t2=threading.Thread(target=func_2,args=())
    t1.start()
    t2.start()
    t1.join()
    t2.join()